BUILD-OUT: ex1 ex3 ex4 ex5 ex6 ex7 ex8 ex9 ex10
all: clean ex1.c ex3.c ex4.c ex5.c ex6.c ex7.c ex8.c ex9.c ex10.c
	make $(BUILD-OUT)
clean:
	rm -f ex1 ex3 ex4 ex5 ex6 ex7 ex8 ex9 ex10
	rm -rf *.dSYM/
