SOURCES: ex1 ex3 ex4 ex5 ex6 ex7 ex8 ex9 ex10 ex11 ex12 ex13
all:  ex1.c ex3.c ex4.c ex5.c ex6.c \
 ex7.c ex8.c ex9.c ex10.c ex11.c ex12.c \
 ex13.c
	make $(SOURCES)
clean:
	rm -f ex1 ex3 ex4 ex5 ex6 ex7 ex8 ex9 ex10 ex11 ex12 ex13
	rm -rf *.dSYM/
